Repository GSG-K3/bills-system-analysis, pull requests merged in 2020-07, with the labels that each got.

#36 Setup file project
  .eslintrc.json
  .prettierrc
  .travis.yml
  Server/app.js
  Server/controllers/index.js
  Server/server.js
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/common-components/Header/index.js
  client/src/components/LandingPage/Style.js
  client/src/components/LandingPage/index.js
  client/src/components/Router.js
  client/src/index.css
  client/src/index.js
  package-lock.json
  package.json
Labels: approved

#42 Update ignore
  .gitignore
  client/.gitignore
  client/package-lock.json
  package-lock.json
Labels: approved

#44 add Heroku link and Used Tecknologis subtitles to read me file #17
  README.md
Labels: approved

#53 File structure
  Server/database/query/Bills/index.js
  Server/helpers/Constants.js
  Server/helpers/responseMessage.js
Labels: approved

#60 create material ui #59
  client/src/Theme/MaterialTheme.js
  client/src/index.js
  package.json
Labels: approved

#62 Loader Progress Component #61
  client/src/common-components/LoaderProgress/index.js
  client/src/common-components/LoaderProgress/style.js
Labels: approved

#57 Database/query/personalinfo
  Server/controllers/User/getPersonalInfo.js
  Server/controllers/User/index.js
  Server/controllers/index.js
  Server/database/query/User/getPersonalinfo.js
  Server/database/query/User/index.js
Labels: approved

#67 delete the file to change its name
  Server/database/query/User/getPersonalInfo.js
Labels: approved

#55 Query to login into the website
  Server/controllers/User/index.js
  Server/controllers/User/logIn.js
  Server/controllers/index.js
  Server/database/query/User/index.js
  Server/database/query/User/logIn.js
  Server/helpers/Validation.js
Labels: awaiting-review

#58 adding query get last 5 bills #48
  Server/controllers/Bill/getLastBill.js
  Server/controllers/Bill/index.js
  Server/controllers/index.js
  Server/database/query/Bills/getLastBill.js
  Server/database/query/Bills/index.js
Labels: approved

#68 Client/component/home
  client/src/assets/communication.svg
  client/src/assets/electricity.svg
  client/src/assets/internet.svg
  client/src/assets/water.svg
  client/src/components/Home/index.js
  client/src/components/Home/style.js
  client/src/components/Router.js
Labels: approved

#75 Client/Login
  client/src/components/Login/index.js
  client/src/components/Login/style.js
  client/src/components/Router.js
Labels: approved

#70 Client/statistics
  Server/controllers/Bill/getBillStatistics.js
  Server/controllers/Bill/index.js
  Server/controllers/index.js
  Server/database/dummyData.sql
  Server/database/query/Address/getAddressById.js
  Server/database/query/Address/index.js
  Server/database/query/Bills/getBillById.js
  Server/database/query/Bills/getBillStatistics.js
  Server/database/query/Bills/index.js
  client/package.json
  client/src/assets/ils.svg
  client/src/components/Router.js
  client/src/components/Statistics/index.js
  client/src/components/Statistics/style.js
Labels: approved, request-changes

#87 Database/query/signup
  Server/controllers/User/index.js
  Server/controllers/User/signUp.js
  Server/controllers/index.js
  Server/database/dbBuild.sql
  Server/database/query/User/index.js
  Server/database/query/User/signUp.js
  Server/helpers/Validation.js
Labels: approved

#92 Resolve "email is found" error message problem
  Server/controllers/User/signUp.js
Labels: approved

#93 Database/query/editprofile
  Server/controllers/Address/getAddressByCity.js
  Server/controllers/Address/getAllAdresses.js
  Server/controllers/Address/index.js
  Server/controllers/User/index.js
  Server/controllers/User/updateUser.js
  Server/controllers/index.js
  Server/database/dbBuild.sql
  Server/database/query/Address/getAddressByCity.js
  Server/database/query/Address/getAllAddresses.js
  Server/database/query/Address/index.js
  Server/database/query/User/index.js
  Server/database/query/User/updateUser.js
Labels: approved

#82 Client/Sign-up
  client/src/components/Router.js
  client/src/components/Signup/index.js
  client/src/components/Signup/style.js
Labels: approved

#96 Create authentication middleware
  Server/controllers/Bill/getBillStatistics.js
  Server/controllers/Bill/getLastBill.js
  Server/controllers/Bill/getUserBillType.js
  Server/controllers/User/getPersonalInfo.js
  Server/controllers/User/updateUser.js
  Server/controllers/index.js
  Server/database/query/User/getUserId.js
  Server/database/query/User/index.js
  Server/middlewares/authentication.js
Labels: approved

#73 create tab for bill page #72
  Server/controllers/Provider/getProviderById.js
  Server/controllers/Provider/index.js
  Server/controllers/index.js
  Server/database/query/Provider/getProviderById.js
  Server/database/query/Provider/index.js
  client/src/components/Bills/index.js
  client/src/components/Bills/style.js
  client/src/components/Router.js
Labels: approved

#94 landing page #22
  client/src/components/LandingPage/Style.js
  client/src/components/LandingPage/index.js
Labels: approved

#100 Eror404
  client/src/components/Errors/Error404/index.js
  client/src/components/Errors/Error404/style.js
  client/src/components/Router.js
Labels: approved

#101 delete the style file because the heruko dose not recognize it
  client/src/components/LandingPage/index.js
  client/src/components/LandingPage/style.js
Labels: approved

#89 new Bill Page #37
  Server/controllers/Bill/getBillType.js
  Server/controllers/Bill/index.js
  Server/controllers/Bill/newBill.js
  Server/controllers/Provider/getProviderByType.js
  Server/controllers/Provider/index.js
  Server/controllers/index.js
  Server/database/query/Bills/index.js
  Server/database/query/Bills/newBill.js
  Server/database/query/Provider/getProviderByType.js
  Server/database/query/Provider/index.js
  Server/helpers/Validation.js
  client/src/Theme/MaterialTheme.js
  client/src/components/NewBill/index.js
  client/src/components/NewBill/style.js
  client/src/components/Router.js
Labels: approved

#104 Disable autocomplete property
  client/src/components/Login/index.js
  client/src/components/Signup/index.js
Labels: approved

#106 Edit message when password contains special characters.
  Server/controllers/User/signUp.js
Labels: approved

#110 numeric-input in package.json
  client/package.json
Labels: approved

#102 authentication
  Server/controllers/Bill/newBill.js
  Server/controllers/index.js
Labels: approved

#109 Take bill type from props in statistics and bills pages.
  client/src/components/Bills/index.js
  client/src/components/LandingPage/index.js
  client/src/components/Router.js
  client/src/components/Statistics/index.js
Labels: approved

#112 Client/component/menu
  Server/controllers/User/index.js
  Server/controllers/User/logOut.js
  Server/controllers/index.js
  client/src/components/Menu/index.js
Labels: approved

#111 Fixed bugs
  client/src/components/Bills/index.js
  client/src/components/NewBill/index.js
Labels: approved

#99 Add login authentication to the client-side #98
  client/src/components/Bills/index.js
  client/src/components/Home/index.js
  client/src/components/NewBill/index.js
  client/src/components/PersonalInfo/index.js
  client/src/components/Router.js
  client/src/components/Statistics/index.js
Labels: approved

#113 Add menu to pages
  Server/controllers/User/index.js
  Server/controllers/User/logOut.js
  Server/controllers/index.js
  client/src/common-components/Menu/index.js
  client/src/components/Bills/index.js
  client/src/components/Home/index.js
  client/src/components/Login/index.js
  client/src/components/NewBill/index.js
  client/src/components/PersonalInfo/index.js
  client/src/components/Statistics/index.js
Labels: approved

#114 fix bugs
  Server/controllers/Address/getAddressByCity.js
  Server/controllers/Address/index.js
  Server/controllers/Provider/getProviderById.js
  Server/controllers/User/signUp.js
  Server/database/query/Bills/getLastBill.js
  Server/database/query/Bills/newBill.js
  Server/database/query/Provider/getProviderById.js
  Server/database/query/User/updateUser.js
  Server/helpers/Validation.js
  client/src/Theme/MaterialTheme.js
  client/src/common-components/Header/index.js
  client/src/components/Bills/index.js
  client/src/components/Login/index.js
  client/src/components/Login/style.js
  client/src/components/NewBill/index.js
  client/src/components/NewBill/style.js
  client/src/components/PersonalInfo/index.js
  client/src/components/PersonalInfo/style.js
  client/src/components/Router.js
  client/src/components/Signup/index.js
  client/src/components/Signup/style.js
  client/src/components/Statistics/index.js
Labels: approved

#116 Replace Link for signup botton to onClick method
  client/src/components/LandingPage/index.js
Labels: approved

#117 fix bugs in address when user choose town from another city
  Server/controllers/User/updateUser.js
  Server/database/query/Address/checkTown.js
  Server/database/query/Address/index.js
Labels: approved
